"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var units_controller_js_1 = require("../controllers/master/units.controller.js");
var countries_controller_js_1 = require("../controllers/master/countries.controller.js");
var continents_controller_js_1 = require("../controllers/master/continents.controller.js");
var router = (0, express_1.Router)();
router.route("/units").get(units_controller_js_1.getUnits);
router.route("/countries").get(countries_controller_js_1.getCountries);
router.route("/continents").get(continents_controller_js_1.getContinents);
router.route("/continent/create").post(continents_controller_js_1.createContinent);
exports.default = router;
